name: topup_application
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - image/
    - font/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: font/PlusJakartaSans.ttf
